[AccessTransformers]

; Custom FGIconLibrary
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ID")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="IconType")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ItemDescriptor")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="DisplayNameOverride")

; Allow setting the material of the widget sign for Sponsor Billboards
BlueprintReadWrite=(Class="/Script/FactoryGame.FGBuildableWidgetSign", Property="mSignProxyPlane")